### ISSUE TITLE
Previous merge conflict

### ISSUE THREAD

**Issue by UgnilJoZ** [myoung008/walking_light#3]
```
<<<<<<< HEAD
Code version A
======
Code version B
>>>>>>> 713681cb6d2d39cb55d4e23eb9c42d2e9cd81f2e
```

The repo is not in a consistent state, there are artifacts from the last merge in the init.lua.
http://githowto.com/resolving_conflicts

**Comment by myoung008** [comment]
Sorry about that.  I got distracted halfway through.  It's fixed now.

**Comment by UgnilJoZ** [comment]
Wow, that was incredibly fast ^^

**Comment by myoung008** [comment]
I found it an hour or so ago and fixed it locally, just had to commit and push.
