### ISSUE TITLE
Please move back torch to hand

### ISSUE THREAD

**Issue by amadin** [myoung008/walking_light#4]
Please move torch with light back to hand. For low CPU load on public server.

**Comment by myoung008** [comment]
I'm sorry, I don't understand what you're asking.  Could you be more specific?

**Comment by amadin** [comment]
In original mod a torch create light only in player's hand. In your mod torch create light if it is in inventory. I ask to change torch light like in original mod, that torch create light only in player's hand. I think your mod use too much processor time on public server.

**Comment by myoung008** [comment]
This version uses far less processor time than the original mod.  That's one of the main reasons I forked it.  Most of the processor time is in calculating the light itself (in the Minetest engine, not the mod).  My version causes the engine to recalculate light far less than in the original (about 1/3).

I'll look in to creating a flag that allows disabling the extra checks for inventory.  You'll have to change the setting in the mod after you download it, but I'll make it easy to do.  It might be a few days.  Between holidays and work I'm pretty swamped right now.

**Comment by myoung008** [comment]
There is an option for this behavior now.  Line 1: local wielding_only = true
The default is false so you will need to change it after pull.

**Comment by amadin** [comment]
Thanks.
